### ISSUE TITLE
Initial setup survey pops up on all machines extension is synced to

### ISSUE THREAD

**Issue by zetafunction** [GoogleChrome/experience-sampling#120]
It would be nice to only pop up the survey on the instance of Chrome where the "add" button was explicitly clicked. No idea if the extension can differentiate this itself though.

**Comment by adrifelt** [comment]
There's no way to differentiate this, but the surveys *should* close themselves once you have responded to the first one.

**Comment by adrifelt** [comment]
@egmorant I think I fixed this, but it could use some testing. Could you help? Do you have multiple computers you could test this out with?

**Comment by egmorant** [comment]
Do you have a version of the extension on the CWS that doesn't require google.com credentials?

**Comment by adrifelt** [comment]
No, it has to remain restricted for now unfortunately. I can give you a .crx but I don't remember whether that will lead to syncing.

**Comment by egmorant** [comment]
Ah, ok. My logged-in Chromebook is at my desk, which I won't be returning to until Wednesday. I can enlist the help of a friend or two in the meantime :)

**Comment by egmorant** [comment]
Just had a friend test out the extension. She was still prompted to fill out the demographic survey twice. Steps to reproduce:
1. Install extension to corp laptop 
2. Fill out demographic survey
3. Navigate to known error throwing site, confirm notification appears. 
4. Login to corp Chrome on workstation
5. Prompted to fill out demographic survey 

Is there any debug info that would be helpful?

**Comment by egmorant** [comment]
Were you able to replicate it? Still need me to test?

**Comment by adrifelt** [comment]
Nope, I'm on it now that I know it's still happening

**Comment by adrifelt** [comment]
This is fixed. It pops up on both computers, but as soon as one is filled out, it closes on the other.
