### ISSUE TITLE
Attributes scale is ambiguous

### ISSUE THREAD

**Issue by moduloprime** [GoogleChrome/experience-sampling#124]
"A great deal" and "very much" sound similar... asedley@ suggests we try either:
A great deal, A lot, A moderate amount, A little, Not at all
or
Completely, Mostly, Moderately, A little, Not at all

**Comment by adrifelt** [comment]
Hey, have you picked one of these? I'm trying to close out all bugs by Friday.

**Comment by moduloprime** [comment]
Let's go with the first: A great deal, A lot, A moderate amount, A little, Not at all. So, delta from current version should be just Very much --> A lot
