### ISSUE TITLE
JSON format not accepted by parsers

### ISSUE THREAD

**Issue by moduloprime** [GoogleChrome/experience-sampling#131]
The current JSON  data files produced are of the form:
{survey result}
{survey result}
...

The python JSON parser I tried was unhappy with this; it wants something like:
{"data array": [
  {survey result},
  {survey result}...
]}

**Comment by adrifelt** [comment]
@moduloprime how are you planning to process the data? do you want to add your processing scripts to the repo? that might give insight into the right way to handle this

**Comment by moduloprime** [comment]
Working on Python processing script now to clean up JSON results and output CSV that we can read into Spreadsheets or R. Will script add to repo. Can you do reviews?

**Comment by adrifelt** [comment]
I can review Python, as can meacer. LMK if you still need me to make changes to backend.

**Comment by meacer** [comment]
I'm back this week, feel free to send reviews to me as well.

**Comment by meacer** [comment]
Coming back from https://github.com/GoogleChrome/experience-sampling/pull/163/files, the processing script seems to have some custom code to work around this limitation.

The export seems to be done in https://github.com/GoogleChrome/experience-sampling/blob/master/backend/export.py. On line 84/85, |delim| is empty string. Should it be? I feel like wrapping the results into [{...}, {...}] in the export string should solve this issue?

**Comment by moduloprime** [comment]
Now JSON output looks like:
[{survey_result},
{survey_result},
...
{survey_result}]
