### ISSUE TITLE
Possible privacy leak in responses to page-source question

### ISSUE THREAD

**Issue by moduloprime** [GoogleChrome/experience-sampling#137]
The current page source question, "Who was the page from?", includes the domain as a possible response, and we might capture this on the backend even when the user has asked not to share the URL with us.

Similar to #128, but I'm not sure whether the fix to #128 addresses responses as well as questions.

**Comment by adrifelt** [comment]
This was fixed with #146  although it ended up landing as #147 because version control is confusing.
