### ISSUE TITLE
Survey notification shouldn't popup if interstitials were kept open for a long time.

### ISSUE THREAD

**Issue by meacer** [GoogleChrome/experience-sampling#177]
The scenario is:
- Open a broken SSL page / malware page.
- Browse memes and cat gifs for 10 mins in another tab.
- Switch to the interstitial and close it.

The survey notification pops up. But at that point I've already forgotten that I navigated to this tab, so I find the "you clicked 'back to safety'" question in the survey confusing. I feel it'll be good to ignore the notification if the tab has been open for a few minutes.

I think this should be implementable using chrome.tabs API and by keeping track of last navigation times?

**Comment by adrifelt** [comment]
Hmmm. But you *did* just see it. It seems more like our questions should have an option for "I have no idea why I'm seeing this" @moduloprime

**Comment by meacer** [comment]
How about showing the survey if the tab was in the foreground when closed? Saying "you clicked back to safety" for a background tab adds to the confusion.
I guess "I have no idea why I'm seeing this" option also works.

**Comment by moduloprime** [comment]
Ok, based on this and the other recent bit of feedback, I'm going to look
into re-opening the survey content and see if we can add some clarifying
options.

**Comment by meacer** [comment]
It looks like I was confused by my own bug report, so Adrienne's comment makes sense now :) Here is the scenario I meant in my second comment:

- Open a broken SSL page / malware page.
- Browse memes and cat gifs for 10 mins in another tab.
- Realize you are a dog person and close the window with all the cat tabs in a fury
- See the survey notification (?)

I believe the survey notification is still displayed if the interstitial tab is in the background which was the part I found confusing. If that's not the case, then please ignore this comment :)

**Comment by adrifelt** [comment]
Ohh, OK. Yeah that's a completely different situation. ;)

Unfortunately I don't think I have any technical way to tell which tab is in the background. I could listen for chrome.tabs onReplaced and onRemoved, but they say whether the closed tab was in the background.

The only way we could handle this case is by having more "i don't know" options like Rob suggested.

**Comment by moduloprime** [comment]
Added "I don't know" options to page-source (and dialog-source), page-referrer, and trust questions. See PR #187. Now all survey questions are either open-ended, so you can just type "I don't know", or they have an I don't know/I'm not sure response. Except for the May we record the URL question, to which the participant can say No.
