### ISSUE TITLE
Ignoring the notification and navigating to some warning URL doesn't show up the notification

### ISSUE THREAD

**Issue by tkonchada** [GoogleChrome/experience-sampling#191]
OS : Windows 8

Steps to reproduce
1. Install the extension https://chrome.google.com/webstore/a/google.com/detail/chrome-user-experience-su/hgimloonaobbeeagepickockgdcghfnn
2. Navigate to https://test.hstsfail.appspot.com and observe that the CUES notification displayed at the bottom of the screen.
3. Ignore the notification and again reload the page - observe

Expected Output:
The  notification should display as the survey is not taken up before

Actual Output:
The notification displays after some time(5 mins) as if the survey was finished before.

**Comment by tkonchada** [comment]
Tested on Chrome version 44.0.2363.0

**Comment by durgaprasad2** [comment]
Issue is observed on Mac 10.9.5 using M 44.0.2363.0 as well.

**Comment by adrifelt** [comment]
I believe this is WAI, we don't survey people again if they've recently been surveyed.
