### ISSUE TITLE
Horizontal and vertical scroll bars not identical when the window is resized

### ISSUE THREAD

**Issue by tkonchada** [GoogleChrome/experience-sampling#192]
OS : Windows 8
Chrome Version : 44.0.2363.0 
Steps to reproduce
1. Install the extension https://chrome.google.com/webstore/a/google.com/detail/chrome-user-experience-su/hgimloonaobbeeagepickockgdcghfnn
2. Minimize the browser window and navigate to https://test.hstsfail.appspot.com and observe that the CUES notification displayed at the bottom of the computer screen
3. Click on "Take Survey" in the notification and observe the survey window in the browser

Expected Output:
Horizontal and vertical scroll bars should be identical

Actual Output:
Horizontal and vertical scroll bars are not identical
![unidentical scrollbars](https://cloud.githubusercontent.com/assets/7567099/7086942/f281631e-dfa3-11e4-89e8-e5a1dcc9357a.png)

**Comment by durgaprasad2** [comment]
Issue is observed on Mac 10.9.5 using M 44.0.2363.0 as well.

**Comment by adrifelt** [comment]
Valid bug, but fix not making the launch.
