### ISSUE TITLE
After clicking on "What is this ?", user is not able to participate in the survey. 

### ISSUE THREAD

**Issue by durgaprasad2** [GoogleChrome/experience-sampling#193]
OS : Mac 10.9.5
Chrome Version : 44.0.2363.0 canary

Steps to reproduce the issue:
1) Add the CUES extension
2) Navigate to SSL warning/malware warning/phishing warning
3) Survey notification window shows up
4) Click on the What's is this ?
5) CUES survey details page opens up.

Actual Result:
User can not participate in the Survey for that session./Page.

Expected Result:
User should have option in the page if he wants participate in the survey. 

![screen shot 2015-04-10 at 4 47 22 pm](https://cloud.githubusercontent.com/assets/11886142/7086873/7a5ad974-dfa3-11e4-8b2a-1ad94b5dc0de.png)

**Comment by durgaprasad2** [comment]
Issue is observed on Win 7 using M 44.0.2363.0 as well.

**Comment by adrifelt** [comment]
@moduloprime @egmorant What do you think? I see a few options:

A) Clicking on 'what is this' will bring up *both* the survey window and the consent page, with the consent page on top.

B) Add a link from the consent page to the survey window. This might be a little messy to implement.

C) Something else?

**Comment by moduloprime** [comment]
I guess I like (B), which seems to involve implementing a new consent page
customized for the "What is this?" scenario. If we do that, we could add a
little explanation on the new consent page saying something along the lines
of, "you previously installed the CUES extension and consented to receive
occasional surveys. To proceed to the survey, click here. To uninstall the
extension, click here. See the consent form for the extension below."

**Comment by egmorant** [comment]
Could you explain a little more about what A would entail? I don't understand what it would mean to have the consent page "on top" of the survey window.

**Comment by adrifelt** [comment]
(A) means I would open two tabs in the same window. The consent tab would be the one in the foreground.
