### ISSUE TITLE
Notification for CUES is not seen on Incognito window.

### ISSUE THREAD

**Issue by durgaprasad2** [GoogleChrome/experience-sampling#194]
OS : Mac 10.9.5
Chrome Version : 44.0.2363.0

Steps to reproduce the issue:
1) Add the CUES extension
2) Navigate to Chrome://extensions and check the Allow in incognito mode check box
3) Navigate to SSL warning/malware warning/phishing warning

Actual Result:
Survey notification window is not shown up.

Expected Result:
Survey notification window should show up.

**Comment by durgaprasad2** [comment]
Issue is observed on Win 7 using M 44.0.2363.0 as well.

**Comment by adrifelt** [comment]
Glad you tested this, as I hadn't. However: this is desired behavior. We do not want to survey about Incognito behavior. Thanks!
