### ISSUE TITLE
Survey triggers when the user cancels the addition of extension

### ISSUE THREAD

**Issue by tkonchada** [GoogleChrome/experience-sampling#195]
OS : Windows 8, Mac 10.9
Chrome Version : 44.0.2363.0 

Steps to reproduce
1. Install the extension https://chrome.google.com/webstore/a/google.com/detail/chrome-user-experience-su/hgimloonaobbeeagepickockgdcghfnn
2. Navigate to Chrome Web Store and add an extension or app
3. In the "Confirm New Extension" popup click on "Delete" button and observe the survey notification.

Expected Output:
The Survey notification should not display as the user is not adding the extension
Actual Output:
Survey notification displays

Please find the screen cast for your reference.

**Comment by durgaprasad2** [comment]
Unable to upload the .mp4 file hence added the screen shot for the same.
![cues_notification on cancel of extn](https://cloud.githubusercontent.com/assets/11886142/7087706/a20e51c8-dfab-11e4-9af5-555d86070dd0.png)

**Comment by adrifelt** [comment]
We meant this to be expected behavior. (The survey should still happen even if the user clicked 'cancel'.) But, let me re-examine that. Why did you find the survey notification surprising in this situation?

**Comment by tkonchada** [comment]
As per the mail, the survey should be displayed when installing an extension/app. But here it is triggering when user clicks on the "cancel" button which means user is not installing the extension.
