### ISSUE TITLE
CUES Extension not uninstalled after 120 days.

### ISSUE THREAD

**Issue by ligimole** [GoogleChrome/experience-sampling#197]
OS : Windows7
Chrome Version : 44.0.2368.0 (Official Build) (32-bit)

Steps to reproduce
1. Install the extension https://chrome.google.com/webstore/a/google.com/detail/chrome-user-experience-su/hgimloonaobbeeagepickockgdcghfnn
2. Acknowledge for CUES survey.
3. Complete the survey form & submit.
4. Change the system date to more than 120 days ahead.( I changed to Aug 1,2015)
5. Exit & relaunch chrome.

Expected
Extension will be automatically uninstalled.

Observed
Extension not uninstalled as per the specification ( uninstall itself after 120 days.)

**Comment by ligimole** [comment]
This issue is filed by Chrome Test Engineering Team.

**Comment by adrifelt** [comment]
@meacer Do you know how extension events are dispatched? Should setting the clock forwards cause a timer to fire as you would expect?

**Comment by meacer** [comment]
The alarms API used in the extension to implement the uninstall feature uses a one shot timer, so I don't expect changing the date to affect the alarm at all.
I think if you really want this to work you'll need to record the installation date.

**Comment by adrifelt** [comment]
I tested this by changing the time constant to a few minutes instead of 120 days. It does in fact uninstall.
