### ISSUE TITLE
Support link in Chrome Web Store doesn't work

### ISSUE THREAD

**Issue by christhompson** [GoogleChrome/experience-sampling#198]
From the extension page in the CWS, https://chrome.google.com/webstore/detail/chrome-user-experience-su/hgimloonaobbeeagepickockgdcghfnn/support, the "support site" link points to https://docs.google.com/document/d/17yc9Z4u5AtU5ZA1agjI8e5tu0rU4bUNmHM12AgeScs4/edit which is a private doc.

**Expected behavior:** Support link should point to a public page with more information about the CUES extension and study, possibly with a way to leave feedback/ask questions.

**Comment by adrifelt** [comment]
@egmorant I can't assign this one to you b/c you aren't a github project member, but can you take care of this pls?

**Comment by egmorant** [comment]
I created a new, public survey: https://docs.google.com/document/d/1OzJE6grqhDgHYnMHOgOH0tPujYfPKFTWFZjO56FbmuE/edit#heading=h.57jf4sio3gb9

I tried updating the extension but am seemingly unable to republish without paying the fee.

**Comment by adrifelt** [comment]
Can you go to File > Publish to the Web and share that link instead? Then I can republish.

**Comment by egmorant** [comment]
https://docs.google.com/document/d/1OzJE6grqhDgHYnMHOgOH0tPujYfPKFTWFZjO56FbmuE/pub

**Comment by adrifelt** [comment]
Pushed.
