### ISSUE TITLE
Move screenshot caption text to be fixed below screenshot.

### ISSUE THREAD

**Issue by moduloprime** [GoogleChrome/experience-sampling#208]
Currently the caption text, "You just now saw a page like the one shown above. The following questions are about that page." scrolls with the survey.

Serge picked up on this. Should we change it? @adrifelt wdyt?

**Comment by adrifelt** [comment]
I don't have a strong opinion. But be aware that there's a tradeoff: putting it above the scroll window further decreases the amount of available space for reading the actual questions.

**Comment by moduloprime** [comment]
Agreed, and I think that's why we originally did it that way. I mentioned this to Serge.

Will close as WON'T FIX.
