### ISSUE TITLE
Remove or re-word the technical literacy question

### ISSUE THREAD

**Issue by adrifelt** [GoogleChrome/experience-sampling#213]
![screen shot 2015-04-27 at 12 22 40 pm](https://cloud.githubusercontent.com/assets/4962198/7355657/25059d32-ecd8-11e4-9935-22a88ed47d2e.png)

We got some feedback during the dogfood that this question was intimidating. I believe during a meeting a few weeks ago, Rob said he'd think about whether we should drop it.

@moduloprime @egmorant WDYT? Should we drop the question?

**Comment by adrifelt** [comment]
@moduloprime @egmorant I need to do this soon, any preferences? I will take silence to mean consent. :)

**Comment by egmorant** [comment]
I wouldn't mind dropping it (I find it intimidating), but should we replace it with something else asking about technical skill?

**Comment by moduloprime** [comment]
Ok.

**Comment by moduloprime** [comment]
How would we feel about a shorter tech literacy question, where we used, say, 4 questions instead of 8?

**Comment by adrifelt** [comment]
I think that would be an improvement

(BTW I didn't really delete it, it's currently commented out, so easy to tweak and add back.)

**Comment by moduloprime** [comment]
I will take this, but it's looking unlikely I'll get to it today.

**Comment by adrifelt** [comment]
I need to do a full testing pass before we launch. I expect it will take an entire day for me to do it across all platforms (CrOS, Win, Mac, Lnx). If I find any bugs, I need to then have a second day of leeway to fix them and re-test. That means that I need all changes to be in today, otherwise I will have to work on this over the weekend.

**Comment by moduloprime** [comment]
Update: we decided today to move launch to 5/11 and code freeze to Friday,
so I should be able to get this done for code freeze.
