### ISSUE TITLE
"Other" open ended text is not being recorded

### ISSUE THREAD

**Issue by adrifelt** [GoogleChrome/experience-sampling#222]
When someone clicks "Other", we offer a box to write an alternate response. Currently that is not being recorded.

**Comment by moduloprime** [comment]
I think the only problem with commas is that my latest fix #221 uses commas to separate the items in the list of multiple checkbox responses. Instead, we should probably let an answer be a json list. Then we can include other responses as free text with commas.

**Comment by moduloprime** [comment]
Documenting what we decided today:
Fixed response questions with an Other field will always have an extra question/answer pair sent back that contains either the participant's Other text or NOANSWER

**Comment by adrifelt** [comment]
@moduloprime be aware that the following can happen:

1. Someone chooses 'Other'
2. Fills out the freeform field
3. Goes back to a different, non-Other response

The freeform field may remain populated if they dont' delete it. So be aware of that and always verify that the answer for the main question is 'other' before grabbing the freeform field.

**Comment by moduloprime** [comment]
Noted. I think this will not be a problem in practice, because we'll always analyze results of the actual answer field before looking at the freeform text.
