### ISSUE TITLE
Extension permission string should be blurred out

### ISSUE THREAD

**Issue by adrifelt** [GoogleChrome/experience-sampling#228]
The permission string in the prompt should be blurred out too, or else people might think that the extension they just installed had that same permission.

![screen shot 2015-04-29 at 8 28 36 am](https://cloud.githubusercontent.com/assets/4962198/7394660/d101be78-ee49-11e4-8949-d7705cf572d3.png)

**Comment by adrifelt** [comment]
@moduloprime can you do this one? i'm not sure how to get the same blur effect that you used

**Comment by moduloprime** [comment]
I will take it

**Comment by moduloprime** [comment]
Fixed with #236
