### ISSUE TITLE
Make the HTTP/HTTPS survey questions more clear

### ISSUE THREAD

**Issue by adrifelt** [GoogleChrome/experience-sampling#232]
Right now it isn't clear which "symbol" is being referred to. Either:

1) Add the symbol inline with the question in parens
2) Circle the symbol in the screenshot

**Comment by moduloprime** [comment]
Assigning myself, since I'm working on the circled screenshots as part of the question wording bug

**Comment by moduloprime** [comment]
See PR #241

**Comment by moduloprime** [comment]
Assigning to @adrifelt to close or add embedded images of symbols in the questions if you want.

**Comment by adrifelt** [comment]
I think the circling is clear, thanks for doing that! Closing.
