### ISSUE TITLE
Windows extension dialog screenshot is irregular with extra text

### ISSUE THREAD

**Issue by moduloprime** [GoogleChrome/experience-sampling#237]

**Comment by adrifelt** [comment]
![screen shot 2015-04-30 at 11 24 04 am](https://cloud.githubusercontent.com/assets/4962198/7419676/7ee930c0-ef2b-11e4-8aac-ec6f4a3a3c19.png)

Here's a Windows screenshot, back to you

**Comment by moduloprime** [comment]
Fixed with PR #242

**Comment by meacer** [comment]
Hmm, maybe it's my machine but that screenshot looks pixelated? Attaching another one just in case.
![windows_crx_install](https://cloud.githubusercontent.com/assets/1571579/7420384/ddb65556-ef30-11e4-8eac-d2f586764776.png)
