### ISSUE TITLE
"How did you find this?" should be multiple choice

### ISSUE THREAD

**Issue by adrifelt** [GoogleChrome/experience-sampling#260]
Options...

* Found in the Chrome Web Store
* Social media (Facebook, Twitter)
* A news article
* Other: [_________]

**Comment by adrifelt** [comment]
@egmorant what do you think of these as starter options?

**Comment by egmorant** [comment]
Is there a way to have an option for people to enter what news article or who's social media account they found it in?

**Comment by adrifelt** [comment]
Unfortunately not, unless we go back to making it completely open ended

Also I bet a lot of people will not take the effort to look up the exact news article or social media account :(

**Comment by egmorant** [comment]
Don't we lose specificity with these preselected options then?

**Comment by adrifelt** [comment]
It depends on what we expect people will say. If they say "Matt Cutts" then we lose specificity. If they say "browsing around" then we gain specificity.

**Comment by moduloprime** [comment]
I think we'd be better off with open-ended. If we get a bunch of people
answering "Facebook/Twitter", that seems not super-helpful. Open-ended will
lead to some generic, non-helpful responses, but it will also I think give
more insight into how the message gets spread around, and the percentage
from different sources.

**Comment by adrifelt** [comment]
OK, sounds good. Less work for me. :)

However looking at the friends-and-family responses, I don't think we are going to get anything useful either way. So we need to be prepared to not be able to tell people apart by installation source.

**Comment by moduloprime** [comment]
I'm prepared. Our recruiting strategy is going to be scattershot, so I
think we need to use the other demographic data to evaluate the diversity
of our sample anyway.
