### ISSUE TITLE
DendoPort

### ISSUE THREAD

**Issue by tomagladiator** [GoogleChrome/experience-sampling#270]
Hello,
I'm curious because I have no clue what is DendoPort ?

Thnaks

**Comment by adrifelt** [comment]
we made up DendoPort. :smile: we added one fake one in case someone might put "full understanding" for all of them without really understanding what the terms meant.

but we've gotten so many questions about it, that I think now we're going to need to release something named DendoPort! :shipit:

**Comment by tomagladiator** [comment]
Ohhhh youuuuuuu ^_^

**Comment by Uutma** [comment]
Hmm. That makes me to have full understanding about what the DendoPort is..... I think I'll cheat this time and choose "no understanding" instead :D

**Comment by richbradshaw** [comment]
But… now I've read this, I do have a full understanding of DendoPort!

**Comment by majard** [comment]
Oh, Google, you're so Sassy. I put "little understanding" because all I knew was that it didn't exist. :D

**Comment by sshum00** [comment]
Wait, now that I know what a DendoPort is.. should I mark full understanding from now on???
