### ISSUE TITLE
Showing too many notifications

### ISSUE THREAD

**Issue by adrifelt** [GoogleChrome/experience-sampling#272]
Some clients are seeing way too many notifications. We have one concrete report with debugging info from Jeroen:
* 10-20 notifications today
* All on the same hostname
* Ubuntu 14.04 with chrome 44.0.2391.0 dev (64-bit)

**Comment by JVApen** [comment]
Extra update; this does not just happen with the invalid certificates;
also with extensions being installed. (Which I was able to reproduce on the chromebook)

**Comment by adrifelt** [comment]
This problem will be fixed with 3.0.3, which I just pushed. Should be live in the CWS in a few minutes.
